// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXxP9Xn-scb-R9Xjir6VVzmXtfV0MC_1w',
    appId: '1:1063713133435:web:9fa129e275c165d5df63de',
    messagingSenderId: '1063713133435',
    projectId: 'login-379f1',
    authDomain: 'login-379f1.firebaseapp.com',
    storageBucket: 'login-379f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArE1I1w7b_e74S8WcTHhc5ML54SR1e-U',
    appId: '1:1063713133435:android:979ec95846ea4dbedf63de',
    messagingSenderId: '1063713133435',
    projectId: 'login-379f1',
    storageBucket: 'login-379f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_9gk9_qgA4Xk3zCBrtq3geQE80sImFIc',
    appId: '1:1063713133435:ios:d14489f21817ffb9df63de',
    messagingSenderId: '1063713133435',
    projectId: 'login-379f1',
    storageBucket: 'login-379f1.appspot.com',
    iosBundleId: 'com.example.lgoinUi',
  );
}
